import { IoFootballOutline } from "react-icons/io5";
import indianflage from "../../../public/Homeimages/indian image.jpg";

export const RecentAllImg = [
  {
    id: "145ko5nkji3636773kl",

    img: "/assets/all/1.jpg",
    name: "Hidden",
    icons: "/assets/icons/diamond.webp",
    price: "14.02",
  },
  {
    id: "145ko5nkji3636773kl",
    img: "/assets/all/2.png",
    name: "Kontrol...",
    icons: "/assets/icons/gold.webp",
    price: "15.02",
  },
  {
    id: "145ko5nkji3636773kl",
    img: "/assets/all/3.png",
    name: "Jarvis..",
    icons: "/assets/icons/platinum.webp",
    price: "16.02",
  },
  {
    id: "145ko5nkji3636773kl",
    img: "/assets/all/4.png",
    name: "Kontrol...",
    icons: "/assets/icons/diamond.webp",
    price: "14.02",
  },
  {
    id: "145ko5nkji3636773kl",
    img: "/assets/all/5.jpg",
    name: "Hidden",
    icons: "/assets/icons/gold.webp",
    price: "15.02",
  },
  {
    id: "145ko5nkji3636773kl",
    img: "/assets/all/6.png",
    name: "Jarvis..",
    icons: "/assets/icons/platinum.webp",
    price: "16.02",
  },
  {
    id: "145ko5nkji3636773kl",
    img: "/assets/all/7.jpg",
    name: "Kontrol...",
    icons: "/assets/icons/diamond.webp",
    price: "14.02",
  },
  {
    id: "145ko5nkji3636773kl",
    img: "/assets/all/8.png",
    name: "Hidden",
    icons: "/assets/icons/gold.webp",
    price: "15.02",
  },
  {
    id: "145ko5nkji3636773kl",
    img: "/assets/all/8.png",
    name: "Hidden",
    icons: "/assets/icons/gold.webp",
    price: "15.02",
  },
  {
    id: "145ko5nkji3636773kl",
    img: "/assets/all/8.png",
    name: "Hidden",
    icons: "/assets/icons/gold.webp",
    price: "15.02",
  },
  {
    id: "145ko5nkji3636773kl",
    img: "/assets/all/9.png",
    name: "Jarvis..",
    icons: "/assets/icons/platinum.webp",
    price: "16.02",
  },
  {
    id: "145ko5nkji3636773kl",
    img: "/assets/all/10.png",
    name: "Kontrol...",
    icons: "/assets/icons/diamond.webp",
    price: "14.02",
  },
  {
    id: "145ko5nkji3636773kl",
    img: "/assets/all/11.jpg",
    name: "Hidden",
    icons: "/assets/icons/gold.webp",
    price: "15.02",
  },
  {
    id: "145ko5nkji3636773kl",
    img: "/assets/all/12.png",
    name: "Jarvis..",
    icons: "/assets/icons/platinum.webp",
    price: "16.02",
  },
  {
    id: "145ko5nkji3636773kl",
    img: "/assets/all/13.jpg",
    name: "Kontrol...",
    icons: "/assets/icons/diamond.webp",
    price: "14.02",
  },
  {
    id: "145ko5nkji3636773kl",
    img: "/assets/all/14.png",
    name: "Hidden",
    icons: "/assets/icons/gold.webp",
    price: "15.02",
  },
  {
    id: "145ko5nkji3636773kl",
    img: "/assets/all/15.png",
    name: "Jarvis..",
    icons: "/assets/icons/platinum.webp",
    price: "16.02",
  },
  {
    id: "145ko5nkji3636773kl",
    img: "/assets/all/15.png",
    name: "Jarvis..",
    icons: "/assets/icons/platinum.webp",
    price: "16.02",
  },
  {
    id: "145ko5nkji3636773kl",
    img: "/assets/all/16.png",
    name: "Kontrol...",
    icons: "/assets/icons/diamond.webp",
    price: "14.02",
  },
  {
    id: "145ko5nkji3636773kl",
    img: "/assets/all/17.png",
    name: "Hidden",
    icons: "/assets/icons/gold.webp",
    price: "15.02",
  },
  {
    id: "145ko5nkji3636773kl",
    img: "/assets/all/18.png",
    name: "Jarvis..",
    icons: "/assets/icons/platinum.webp",
    price: "16.02",
  },
];

export const BCOrigin = [
  { img: "/assets/all/3.png", num: 228, name: "Mines" },
  { img: "/assets/all/3.png", num: 225, name: "Mines" },
  { img: "/assets/all/6.png", num: 196, name: "Mines" },
  { img: "/assets/all/8.png", num: 200, name: "Mines" },
  { img: "/assets/all/3.png", num: 225, name: "Mines" },
  { img: "/assets/all/6.png", num: 199, name: "Mines" },
  { img: "/assets/all/8.png", num: 220, name: "Mines" },
  { img: "/assets/all/3.png", num: 223, name: "Mines" },
  { img: "/assets/all/6.png", num: 198, name: "Mines" },
  { img: "/assets/all/6.png", num: 198, name: "Mines" },
  { img: "/assets/all/3.png", num: 225, name: "Mines" },
  { img: "/assets/all/6.png", num: 196, name: "Mines" },
  { img: "/assets/all/6.png", num: 198, name: "Mines" },
  { img: "/assets/all/3.png", num: 225, name: "Mines" },
  { img: "/assets/all/3.png", num: 228, name: "Mines" },
  { img: "/assets/all/6.png", num: 198, name: "Mines" },
  { img: "/assets/all/6.png", num: 196, name: "Mines" },
  { img: "/assets/all/8.png", num: 200, name: "Mines" },
  { img: "/assets/all/3.png", num: 225, name: "Mines" },
  { img: "/assets/all/6.png", num: 199, name: "Mines" },
  { img: "/assets/all/8.png", num: 220, name: "Mines" },
  { img: "/assets/all/3.png", num: 223, name: "Mines" },
  { img: "/assets/all/6.png", num: 198, name: "Mines" },
  { img: "/assets/all/6.png", num: 198, name: "Mines" },
  { img: "/assets/all/3.png", num: 225, name: "Mines" },
  { img: "/assets/all/6.png", num: 196, name: "Mines" },
  { img: "/assets/all/6.png", num: 198, name: "Mines" },
  { img: "/assets/all/3.png", num: 228, name: "Mines" },
  { img: "/assets/all/3.png", num: 225, name: "Mines" },
  { img: "/assets/all/6.png", num: 196, name: "Mines" },
  { img: "/assets/all/8.png", num: 200, name: "Mines" },
  { img: "/assets/all/3.png", num: 225, name: "Mines" },
  { img: "/assets/all/6.png", num: 199, name: "Mines" },
  { img: "/assets/all/8.png", num: 220, name: "Mines" },
  { img: "/assets/all/3.png", num: 223, name: "Mines" },
  { img: "/assets/all/6.png", num: 198, name: "Mines" },
  { img: "/assets/all/8.png", num: 220, name: "Mines" },
  { img: "/assets/all/6.png", num: 198, name: "Mines" },
  {
    slug: "TopPicks",
    data: [
      { img: "/assets/all/3.png", num: 228, name: "Mines" },
      { img: "/assets/all/6.png", num: 19 },
      { img: "/assets/all/6.png", num: 196, name: "Mines" },
      { img: "/assets/all/8.png", num: 200, name: "Mines" },
      { img: "/assets/all/3.png", num: 225, name: "Mines" },
      { img: "/assets/all/6.png", num: 199, name: "Mines" },
      { img: "/assets/all/8.png", num: 220, name: "Mines" },
      { img: "/assets/all/3.png", num: 223, name: "Mines" },
      { img: "/assets/all/6.png", num: 198, name: "Mines" },
      { img: "/assets/all/8.png", num: 20 },
      { img: "/assets/all/3.png", num: 22 },
      { img: "/assets/all/6.png", num: 196, name: "Mines" },
      { img: "/assets/all/6.png", num: 19 },
      { img: "/assets/all/8.png", num: 20 },
    ],
  },
  {
    slug: "slots",
    data: [
      { img: "/assets/all/1.png", num: 300, name: "SuryaGame1" },
      { img: "/assets/all/2.png", num: 150, name: "SuryaGame2" },
      { img: "/assets/all/3.png", num: 120, name: "SuryaGame3" },
      { img: "/assets/all/4.png", num: 99, name: "SuryaGame4" },
      { img: "/assets/all/5.png", num: 250, name: "SuryaGame5" },
    ],
  },
  {
    slug: "Live-Casino",
    data: [
      { img: "/assets/all/3.png", num: 225, name: "Mines" },
      { img: "/assets/all/6.png", num: 199, name: "Mines" },
    ],
  },
  {
    slug: "HotGame",
    data: [
      { img: "/assets/all/8.png", num: 200, name: "Mines" },
      { img: "/assets/all/3.png", num: 225, name: "Mines" },
      { img: "/assets/all/6.png", num: 199, name: "Mines" },
      { img: "/assets/all/8.png", num: 220, name: "Mines" },
      { img: "/assets/all/3.png", num: 223, name: "Mines" },
      { img: "/assets/all/6.png", num: 198, name: "Mines" },
      { img: "/assets/all/8.png", num: 20 },
      { img: "/assets/all/3.png", num: 22 },
      { img: "/assets/all/6.png", num: 196, name: "Mines" },
    ],
  },
  {
    slug: "signin",
    data: [
      { img: "/assets/all/8.png", num: 200, name: "Mines" },
      { img: "/assets/all/3.png", num: 225, name: "Mines" },
      { img: "/assets/all/6.png", num: 199, name: "Mines" },
      { img: "/assets/all/8.png", num: 220, name: "Mines" },
      { img: "/assets/all/6.png", num: 196, name: "Mines" },
    ],
  },
  {
    slug: "signup",
    data: [
      { img: "/assets/all/8.png", num: 200, name: "Mines" },
      { img: "/assets/all/3.png", num: 225, name: "Mines" },
      { img: "/assets/all/6.png", num: 199, name: "Mines" },
      { img: "/assets/all/8.png", num: 220, name: "Mines" },
      { img: "/assets/all/6.png", num: 196, name: "Mines" },
      { img: "/assets/all/8.png", num: 200, name: "Mines" },
      { img: "/assets/all/3.png", num: 225, name: "Mines" },
      { img: "/assets/all/6.png", num: 199, name: "Mines" },
      { img: "/assets/all/8.png", num: 220, name: "Mines" },
      { img: "/assets/all/3.png", num: 223, name: "Mines" },
    ],
  },
  {
    slug: "bingo",
    data: [
      { img: "/assets/all/8.png", num: 200, name: "Mines" },
      { img: "/assets/all/3.png", num: 225, name: "Mines" },
      { img: "/assets/all/6.png", num: 199, name: "Mines" },
      { img: "/assets/all/8.png", num: 220, name: "Mines" },
      { img: "/assets/all/6.png", num: 196, name: "Mines" },
      { img: "/assets/all/8.png", num: 200, name: "Mines" },
      { img: "/assets/all/3.png", num: 225, name: "Mines" },
      { img: "/assets/all/6.png", num: 199, name: "Mines" },
      { img: "/assets/all/8.png", num: 220, name: "Mines" },
      { img: "/assets/all/3.png", num: 223, name: "Mines" },
    ],
  },
  {
    slug: "tableGames",
    data: [
      { img: "/assets/all/8.png", num: 200, name: "Mines" },
      { img: "/assets/all/3.png", num: 225, name: "Mines" },
      { img: "/assets/all/6.png", num: 199, name: "Mines" },
      { img: "/assets/all/8.png", num: 220, name: "Mines" },
      { img: "/assets/all/6.png", num: 196, name: "Mines" },
      { img: "/assets/all/3.png", num: 223, name: "Mines" },
    ],
  },
  {
    slug: "gameShows",
    data: [
      { img: "/assets/all/8.png", num: 200, name: "Mines" },
      { img: "/assets/all/3.png", num: 225, name: "Mines" },
      { img: "/assets/all/6.png", num: 199, name: "Mines" },
      { img: "/assets/all/8.png", num: 220, name: "Mines" },
      { img: "/assets/all/3.png", num: 223, name: "Mines" },
      { img: "/assets/all/6.png", num: 198, name: "Mines" },
      { img: "/assets/all/8.png", num: 20 },
      { img: "/assets/all/3.png", num: 22 },
      { img: "/assets/all/6.png", num: 196, name: "Mines" },
    ],
  },
  {
    slug: "Providers",
    data: [
      { img: "/assets/all/8.png", num: 200, name: "Mines" },
      { img: "/assets/all/3.png", num: 225, name: "Mines" },
      { img: "/assets/all/6.png", num: 199, name: "Mines" },
      { img: "/assets/all/8.png", num: 220, name: "Mines" },
      { img: "/assets/all/3.png", num: 223, name: "Mines" },
      { img: "/assets/all/6.png", num: 196, name: "Mines" },
    ],
  },
  {
    slug: "themes",
    data: [
      { img: "/assets/all/8.png", num: 200, name: "Mines" },
      { img: "/assets/all/3.png", num: 225, name: "Mines" },
      { img: "/assets/all/6.png", num: 199, name: "Mines" },
      { img: "/assets/all/8.png", num: 220, name: "Mines" },
      { img: "/assets/all/3.png", num: 223, name: "Mines" },
      { img: "/assets/all/6.png", num: 196, name: "Mines" },
      { img: "/assets/all/8.png", num: 200, name: "Mines" },
      { img: "/assets/all/3.png", num: 225, name: "Mines" },
      { img: "/assets/all/6.png", num: 199, name: "Mines" },
      { img: "/assets/all/8.png", num: 220, name: "Mines" },
      { img: "/assets/all/3.png", num: 223, name: "Mines" },
    ],
  },
];

export const LiveSports = [
  {
    name: "Soccer",
    title: "3x3 Microfutsal Liga Pro (2x10 min)",
    icons1: <IoFootballOutline />,
    icons2: <IoFootballOutline />,
    subTitle1: "Orion-pro",
    subTitle2: "Neptun-pro",
    time: "0:1",
    startWay: "1st half",
    one: "19.0",
    draw: "5.0",
    two: "1.19",
    three: 3,
  },
  {
    name: "Soccer",
    title: "3x3 Microfutsal Liga Pro (2x10 min)",
    icons1: <IoFootballOutline />,
    icons2: <IoFootballOutline />,
    subTitle1: "Orion-pro",
    subTitle2: "Neptun-pro",
    time: "0:1",
    startWay: "1st half",
    one: "19.0",
    draw: "5.0",
    two: "1.19",
    three: 3,
  },
  {
    name: "Soccer",
    title: "3x3 Microfutsal Liga Pro (2x10 min)",
    icons1: <IoFootballOutline />,
    icons2: <IoFootballOutline />,
    subTitle1: "Orion-pro",
    subTitle2: "Neptun-pro",
    time: "0:1",
    startWay: "1st half",
    one: "19.0",
    draw: "5.0",
    two: "1.19",
    three: 3,
  },
  {
    name: "Soccer",
    title: "3x3 Microfutsal Liga Pro (2x10 min)",
    icons1: <IoFootballOutline />,
    icons2: <IoFootballOutline />,
    subTitle1: "Orion-pro",
    subTitle2: "Neptun-pro",
    time: "0:1",
    startWay: "1st half",
    one: "19.0",
    draw: "5.0",
    two: "1.19",
    three: 3,
  },
  {
    name: "Soccer",
    title: "3x3 Microfutsal Liga Pro (2x10 min)",
    icons1: <IoFootballOutline />,
    icons2: <IoFootballOutline />,
    subTitle1: "Orion-pro",
    subTitle2: "Neptun-pro",
    time: "0:1",
    startWay: "1st half",
    one: "19.0",
    draw: "5.0",
    two: "1.19",
    three: 3,
  },
];

export const BCExclusive = [
  {
    img: "/assets/all/3.png",
    num: 28,
    name: "Mines",
  },
  {
    img: "/assets/all/6.png",
    num: 196,
    name: "Mines",
  },
  {
    img: "/assets/all/8.png",
    num: 200,
    name: "Mines",
  },
  {
    img: "/assets/all/3.png",
    num: 225,
    name: "Mines",
  },
  {
    img: "/assets/all/6.png",
    num: 199,
    name: "Mines",
  },
  {
    img: "/assets/all/8.png",
    num: 220,
    name: "Mines",
  },
  {
    img: "/assets/all/3.png",
    num: 223,
    name: "Mines",
  },
  {
    img: "/assets/all/6.png",
    num: 198,
    name: "Mines",
  },
  {
    img: "/assets/all/8.png",
    num: 20,
  },
  {
    img: "/assets/all/3.png",
    num: 22,
  },
  {
    img: "/assets/all/6.png",
    num: 19,
  },
  {
    img: "/assets/all/8.png",
    num: 20,
  },
];
export const Sports = [
  {
    img: "/assets/all/3.png",
    num: 28,
    name: "Mines",
  },
  {
    img: "/assets/all/6.png",
    num: 196,
    name: "Mines",
  },
  {
    img: "/assets/all/8.png",
    num: 200,
    name: "Mines",
  },
  {
    img: "/assets/all/3.png",
    num: 225,
    name: "Mines",
  },
  {
    img: "/assets/all/6.png",
    num: 199,
    name: "Mines",
  },
  {
    img: "/assets/all/8.png",
    num: 220,
    name: "Mines",
  },
  {
    img: "/assets/all/3.png",
    num: 223,
    name: "Mines",
  },
  {
    img: "/assets/all/6.png",
    num: 198,
    name: "Mines",
  },
  {
    img: "/assets/all/8.png",
    num: 20,
  },
  {
    img: "/assets/all/3.png",
    num: 22,
  },
  {
    img: "/assets/all/6.png",
    num: 19,
  },
  {
    img: "/assets/all/8.png",
    num: 20,
  },
];

export const Upcoming = [
  {
    name: "Rapido Rassia 8/20",
    img: indianflage,
    price: 847463.06,
    startWay: "Next Draw Starts in",
    time: "00:10:12",
  },

  {
    name: "Rapido Rassia 8/20",
    img: indianflage,
    price: 847463.06,
    startWay: "Next Draw Starts in",
    time: "00:15:12",
  },
  {
    name: "Rapido Rassia 8/20",
    img: indianflage,
    price: 847463.06,
    startWay: "Next Draw Starts in",
    time: "00:15:12",
  },
  {
    name: "Rapido Rassia 8/20",
    img: indianflage,
    price: 847463.06,
    startWay: "Next Draw Starts in",
    time: "00:15:12",
  },
  {
    name: "Rapido Rassia 8/20",
    img: indianflage,
    price: 847463.06,
    startWay: "Next Draw Starts in",
    time: "00:15:12",
  },
  {
    name: "Rapido Rassia 8/20",
    img: indianflage,
    price: 847463.06,
    startWay: "Next Draw Starts in",
    time: "00:15:12",
  },
 
];

export const LiveCasino = [
  {
    img: "/assets/all/3.png",
    num: 28,
    name: "Mines",
  },
  {
    img: "/assets/all/6.png",
    num: 196,
    name: "Mines",
  },
  {
    img: "/assets/all/8.png",
    num: 200,
    name: "Mines",
  },
  {
    img: "/assets/all/3.png",
    num: 225,
    name: "Mines",
  },
  {
    img: "/assets/all/6.png",
    num: 199,
    name: "Mines",
  },
  {
    img: "/assets/all/8.png",
    num: 220,
    name: "Mines",
  },
  {
    img: "/assets/all/3.png",
    num: 223,
    name: "Mines",
  },
  {
    img: "/assets/all/6.png",
    num: 198,
    name: "Mines",
  },
  {
    img: "/assets/all/8.png",
    num: 20,
  },
  {
    img: "/assets/all/3.png",
    num: 22,
  },
  {
    img: "/assets/all/6.png",
    num: 19,
  },
  {
    img: "/assets/all/8.png",
    num: 20,
  },
];
export const BingoGame = [
  {
    img: "/assets/all/3.png",
    num: 28,
    name: "Mines",
  },
  {
    img: "/assets/all/6.png",
    num: 196,
    name: "Mines",
  },
  {
    img: "/assets/all/8.png",
    num: 200,
    name: "Mines",
  },
  {
    img: "/assets/all/3.png",
    num: 225,
    name: "Mines",
  },
  {
    img: "/assets/all/6.png",
    num: 199,
    name: "Mines",
  },
  {
    img: "/assets/all/8.png",
    num: 220,
    name: "Mines",
  },
  {
    img: "/assets/all/3.png",
    num: 223,
    name: "Mines",
  },
  {
    img: "/assets/all/6.png",
    num: 198,
    name: "Mines",
  },
  {
    img: "/assets/all/8.png",
    num: 20,
  },
  {
    img: "/assets/all/3.png",
    num: 22,
  },
  {
    img: "/assets/all/6.png",
    num: 19,
  },
  {
    img: "/assets/all/8.png",
    num: 20,
  },
];

export const HoteGame = [
  {
    img: "/assets/all/3.png",
    num: 28,
    name: "Mines",
  },
  {
    img: "/assets/all/6.png",
    num: 196,
    name: "Mines",
  },
  {
    img: "/assets/all/8.png",
    num: 200,
    name: "Mines",
  },
  {
    img: "/assets/all/3.png",
    num: 225,
    name: "Mines",
  },
  {
    img: "/assets/all/6.png",
    num: 199,
    name: "Mines",
  },
  {
    img: "/assets/all/8.png",
    num: 220,
    name: "Mines",
  },
  {
    img: "/assets/all/3.png",
    num: 223,
    name: "Mines",
  },
  {
    img: "/assets/all/6.png",
    num: 198,
    name: "Mines",
  },
  {
    img: "/assets/all/8.png",
    num: 20,
  },
  {
    img: "/assets/all/3.png",
    num: 22,
  },
  {
    img: "/assets/all/6.png",
    num: 19,
  },
  {
    img: "/assets/all/8.png",
    num: 20,
  },
];
